# Generated by Django 2.2.3 on 2019-08-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_tweet_author'),
        ('api', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tweets',
            field=models.ManyToManyField(to='tweets.Tweet'),
        ),
    ]
