# Generated by Django 2.2.3 on 2019-08-06 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userprofile_tweets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='tweets',
            field=models.ManyToManyField(blank=True, to='tweets.Tweet'),
        ),
    ]
