# Generated by Django 2.2.3 on 2019-08-06 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_tweet_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_auto_20190806_0417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='tweets',
        ),
        migrations.CreateModel(
            name='TweetList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet', models.ManyToManyField(blank=True, to='tweets.Tweet')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
