# Generated by Django 2.2.3 on 2019-08-06 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190806_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tweets',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.TweetList'),
        ),
    ]
