# Generated by Django 2.2.3 on 2019-08-06 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_tweet_author'),
        ('api', '0007_userprofile_tweets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='tweets',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tweets',
            field=models.ManyToManyField(blank=True, to='tweets.Tweet'),
        ),
        migrations.DeleteModel(
            name='TweetList',
        ),
    ]
