export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const GET_TWEETS_START = "GET_TWEETS_START";
export const GET_TWEETS_SUCCESS = "GET_TWEETS_SUCCESS";

export const GET_DETAIL_TWEET_START = "GET_DETAIL_TWEET_START";
export const GET_DETAIL_TWEET_SUCCESS = "GET_DETAIL_TWEET_SUCCESS";

export const POST_TWEET_SUCCESS = "POST_TWEET_SUCCESS";
export const POST_TWEET_START = "POST_TWEET_START";

export const DELETE_TWEET_SUCCESS = "DELETE_TWEET_SUCCESS";
export const DELETE_TWEET_START = "DELETE_TWEET_START";

export const UPDATE_TWEET_SUCCESS = "UPDATE_TWEET_SUCCESS";
export const UPDATE_TWEET_START = "UPDATE_TWEET_START";
