# Generated by Django 2.2.3 on 2019-08-01 09:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('follows', '0003_auto_20190801_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follows',
            name='followed_on',
        ),
        migrations.RemoveField(
            model_name='follows',
            name='follows',
        ),
        migrations.AddField(
            model_name='follows',
            name='follows',
            field=models.ManyToManyField(related_name='rel_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
