# Generated by Django 2.2.3 on 2019-08-06 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('follows', '0006_auto_20190806_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follows',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rel_from', to=settings.AUTH_USER_MODEL),
        ),
    ]
